# Generated by Django 2.2.12 on 2020-10-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subservices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subservices', models.CharField(max_length=225)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Services')),
            ],
        ),
    ]
