# Generated by Django 2.2.12 on 2020-10-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='subservices',
            options={'verbose_name': 'Sub Services', 'verbose_name_plural': 'Sub Services'},
        ),
        migrations.AlterModelTable(
            name='services',
            table='table_services',
        ),
        migrations.AlterModelTable(
            name='subservices',
            table='table_subservices',
        ),
    ]
