# Generated by Django 2.2.12 on 2020-10-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201002_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hireus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Hire Us',
                'verbose_name_plural': 'Hire Us',
                'db_table': 'table_hireus',
            },
        ),
        migrations.CreateModel(
            name='Hireuseconn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hireus')),
            ],
            options={
                'verbose_name': 'Hire Us Content',
                'verbose_name_plural': 'Hire Us Content',
                'db_table': 'table_hireuscontent',
            },
        ),
    ]
