# Generated by Django 3.1.1 on 2020-10-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hireus_hireuseconn'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireuseconn',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hireuseconn',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hireuseconn',
            name='heading',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='hireuseconn',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hire_us_images'),
        ),
    ]
