# Generated by Django 2.2.10 on 2020-10-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contact_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
