# Generated by Django 2.2.10 on 2020-10-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201005_0608'),
        ('core', '0007_auto_20201005_0833'),
    ]

    operations = [
    ]
